module.exports = {
  content: ["./client/index.html", "./client/src/**/*.{js,jsx,ts,tsx}",
    "./src/**/*.{html,js,ts,jsx,tsx}",
    "app/**/*.{ts,tsx}",
    "components/**/*.{ts,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        errorred: "var(--errorred)",
        "neutralblack-1000": "var(--neutralblack-1000)",
        "neutralgray-300": "var(--neutralgray-300)",
        "neutralgray-400": "var(--neutralgray-400)",
        "neutralgray-500": "var(--neutralgray-500)",
        "neutralgray-600": "var(--neutralgray-600)",
        "neutralgray-800": "var(--neutralgray-800)",
        neutralwhite: "var(--neutralwhite)",
        "neutralwhite-200": "var(--neutralwhite-200)",
        "primaryblue-violet": "var(--primaryblue-violet)",
        "secondarymedium-orchid": "var(--secondarymedium-orchid)",
        "secondaryneon-blue": "var(--secondaryneon-blue)",
        "secondaryradical-red": "var(--secondaryradical-red)",
        "secondaryspicy-pink": "var(--secondaryspicy-pink)",
        "secondarysummer-sky": "var(--secondarysummer-sky)",
        successgreen: "var(--successgreen)",
        warningyellow: "var(--warningyellow)",
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
      },
      fontFamily: {
        "button-RG": "var(--button-RG-font-family)",
        "caption-RG": "var(--caption-RG-font-family)",
        "heading-h1": "var(--heading-h1-font-family)",
        "heading-h2": "var(--heading-h2-font-family)",
        "heading-h3": "var(--heading-h3-font-family)",
        "heading-h4": "var(--heading-h4-font-family)",
        "heading-h5": "var(--heading-h5-font-family)",
        "heading-h6": "var(--heading-h6-font-family)",
        "paragraph-MD": "var(--paragraph-MD-font-family)",
        "paragraph-RG": "var(--paragraph-RG-font-family)",
        "paragraph-SM": "var(--paragraph-SM-font-family)",
        "subtitle-LG": "var(--subtitle-LG-font-family)",
        "subtitle-RG": "var(--subtitle-RG-font-family)",
        sans: [
          "ui-sans-serif",
          "system-ui",
          "sans-serif",
          '"Apple Color Emoji"',
          '"Segoe UI Emoji"',
          '"Segoe UI Symbol"',
          '"Noto Color Emoji"',
        ],
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
      },
    },
    container: { center: true, padding: "2rem", screens: { "2xl": "1400px" } },
  },
  plugins: [require("tailwindcss-animate"), require("@tailwindcss/typography")],
  darkMode: ["class"],
};
